-- One-off setup for the Sales & Tender Adjustments app. Run as an admin role.
-- Replace <...> placeholders. Run the EDW grants once per database (EDW_TEST, EDW_PROD).

-- ---------------------------------------------------------------------------
-- App audit log — one row per commit attempt (shared by dev and prod)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS STREAMLIT_APPS.DATA_MANAGEMENT.AUDIT_LOG_ADJUSTMENTS (
    TIMESTAMP       TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    USER_NAME       VARCHAR,        -- the app viewer, never CURRENT_USER()
    USER_ROLE       VARCHAR,
    DIVISION        VARCHAR,
    BRAND           VARCHAR,
    STORE_NUMBER    VARCHAR,
    STORE_NAME      VARCHAR,
    ADJUSTMENT_DATE DATE,
    SALES_LINES     NUMBER,
    TENDER_LINES    NUMBER,
    AUDIT_NOTE      VARCHAR,
    OUTCOME         VARCHAR,        -- SUCCESS | PARTIAL | FAILED
    MESSAGE         VARCHAR,
    RECORD_SOURCE   VARCHAR
);

-- ---------------------------------------------------------------------------
-- Git repository + Streamlit objects (reuses the existing API integration)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE GIT REPOSITORY STREAMLIT_APPS.DATA_MANAGEMENT.SALES_TENDER_ADJUSTMENTS
  API_INTEGRATION = GIT_API_INTEGRATION
  GIT_CREDENTIALS = STREAMLIT_APPS.DATA_MANAGEMENT.git_secret
  ORIGIN = 'https://github.com/rbl-biadmin/sales-tender-adjustments.git';

CREATE OR REPLACE STREAMLIT STREAMLIT_APPS.DATA_MANAGEMENT.SALES_TENDER_ADJUSTMENTS_DEV
  ROOT_LOCATION = '@STREAMLIT_APPS.DATA_MANAGEMENT.SALES_TENDER_ADJUSTMENTS/branches/develop'
  MAIN_FILE = 'streamlit_app.py'
  QUERY_WAREHOUSE = 'STREAMLIT_WH'
  TITLE = 'Sales and Tender Adjustments (DEV)'
  COMMENT = 'Sales and Tender Adjustments - DEV version';

CREATE OR REPLACE STREAMLIT STREAMLIT_APPS.DATA_MANAGEMENT.SALES_TENDER_ADJUSTMENTS
  ROOT_LOCATION = '@STREAMLIT_APPS.DATA_MANAGEMENT.SALES_TENDER_ADJUSTMENTS/branches/main'
  MAIN_FILE = 'streamlit_app.py'
  QUERY_WAREHOUSE = 'STREAMLIT_WH'
  TITLE = 'Sales and Tender Adjustments'
  COMMENT = 'Sales and Tender Adjustments - PROD version';

-- ---------------------------------------------------------------------------
-- Grants. Streamlit in Snowflake runs queries with the app OWNER's rights, so
-- the owner role needs every privilege below. The editor role grants are what
-- utils/auth.py checks (directly granted roles only — no inheritance walk).
-- ---------------------------------------------------------------------------
SET APP_OWNER_ROLE = '<APP_OWNER_ROLE>';

-- Editors see the PROD app only; the DEV app is left to RL_STREAMLIT_ADMIN.
GRANT USAGE ON STREAMLIT STREAMLIT_APPS.DATA_MANAGEMENT.SALES_TENDER_ADJUSTMENTS TO ROLE RL_STREAMLIT_EDITOR;
GRANT INSERT, SELECT ON TABLE STREAMLIT_APPS.DATA_MANAGEMENT.AUDIT_LOG_ADJUSTMENTS TO ROLE IDENTIFIER($APP_OWNER_ROLE);

-- Read side (mart)
GRANT SELECT ON EDW_TEST.MART_SALES.DIM_STORES              TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT ON EDW_TEST.MART_SALES.DIM_BRANDS              TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT ON EDW_TEST.MART_SALES.DIM_DIVISIONS           TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT ON EDW_TEST.MART_SALES.DIM_ORDER_CHANNELS      TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT ON EDW_TEST.MART_SALES.DIM_DELIVERY_CHANNELS   TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT ON EDW_TEST.MART_SALES.DIM_PAYMENT_TYPES       TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT ON EDW_TEST.MART_SALES.RPT_DAILY_STORE_SALES   TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT ON EDW_TEST.MART_SALES.RPT_TENDER_MEDIA_SALES  TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT ON EDW_TEST.MART_SALES.FACT_SALES              TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT ON EDW_TEST.MART_SALES.FACT_SALES_ADJUSTMENTS  TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT ON EDW_TEST.MART_SALES.FACT_TENDER_ADJUSTMENTS TO ROLE IDENTIFIER($APP_OWNER_ROLE);

-- Data Vault — the app creates adjustment keys, so MERGE needs SELECT + INSERT
GRANT SELECT ON EDW_TEST.DATAVAULT.REF_BRANDS    TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT ON EDW_TEST.DATAVAULT.REF_DIVISIONS TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT ON EDW_TEST.DATAVAULT.H_STORES      TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT, INSERT ON EDW_TEST.DATAVAULT.H_ADJUSTMENTS_AUDIT  TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT, INSERT ON EDW_TEST.DATAVAULT.S_ADJUSTMENTS_AUDIT  TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT, INSERT ON EDW_TEST.DATAVAULT.H_SALES_ADJUSTMENTS  TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT, INSERT ON EDW_TEST.DATAVAULT.L_SALES_ADJUSTMENTS  TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT, INSERT ON EDW_TEST.DATAVAULT.S_SALES_ADJUSTMENTS  TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT, INSERT ON EDW_TEST.DATAVAULT.H_TENDER_ADJUSTMENTS TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT, INSERT ON EDW_TEST.DATAVAULT.L_TENDER_ADJUSTMENTS TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT SELECT, INSERT ON EDW_TEST.DATAVAULT.S_TENDER_ADJUSTMENTS TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT USAGE ON FUNCTION EDW_TEST.DATAVAULT.UDF_KEY_TO_DATE(NUMBER) TO ROLE IDENTIFIER($APP_OWNER_ROLE);

-- Mart refresh procedures (adjust the signature to match the DDL)
GRANT USAGE ON PROCEDURE EDW_TEST.MART_SALES.SALES_ADJUSTMENTS(VARCHAR, NUMBER, VARCHAR)  TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT USAGE ON PROCEDURE EDW_TEST.MART_SALES.TENDER_ADJUSTMENTS(VARCHAR, NUMBER, VARCHAR) TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT USAGE ON PROCEDURE EDW_TEST.MART_SALES.AGG_DAILY_STORE_SALES(VARCHAR, NUMBER, VARCHAR) TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT USAGE ON PROCEDURE EDW_TEST.MART_SALES.AGG_DAILY_MENU_SALES(VARCHAR, NUMBER, VARCHAR)  TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT USAGE ON PROCEDURE EDW_TEST.MART_SALES.AGG_DAILY_DISCOUNTS(VARCHAR, NUMBER, VARCHAR)   TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT USAGE ON PROCEDURE EDW_TEST.MART_SALES.AGG_TENDER_MEDIA_SALES(VARCHAR, NUMBER, VARCHAR) TO ROLE IDENTIFIER($APP_OWNER_ROLE);
GRANT USAGE ON PROCEDURE EDW_TEST.MART_SALES.LK_TRADING_DAYS(VARCHAR, NUMBER, VARCHAR)    TO ROLE IDENTIFIER($APP_OWNER_ROLE);

-- Editors — granted directly to each user (utils/auth.py does not walk inheritance)
GRANT ROLE RL_STREAMLIT_EDITOR TO USER "<user>";

-- ---------------------------------------------------------------------------
-- CI deploy role RL_STREAMLIT_ADMIN (the SNOWFLAKE_ROLE GitHub secret) — runs ALTER GIT REPOSITORY
-- ... FETCH, which needs WRITE on the repository. CREATE OR REPLACE GIT
-- REPOSITORY above drops these grants, so re-run this block whenever it runs.
-- ---------------------------------------------------------------------------
GRANT USAGE ON DATABASE STREAMLIT_APPS                 TO ROLE RL_STREAMLIT_ADMIN;
GRANT USAGE ON SCHEMA STREAMLIT_APPS.DATA_MANAGEMENT   TO ROLE RL_STREAMLIT_ADMIN;
GRANT READ, WRITE ON GIT REPOSITORY STREAMLIT_APPS.DATA_MANAGEMENT.SALES_TENDER_ADJUSTMENTS TO ROLE RL_STREAMLIT_ADMIN;
